### ISSUE TITLE
Feature: User can set their preferences on types of food and location

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to search for locations by inputting a parameter on food and location.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will arrive at the home page and be able to type in their preference of food and location.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/153960225-3a168571-61b7-4c08-9822-2b9686f2da9a.png)
![image](https://user-images.githubusercontent.com/90667339/153960271-659997f2-aff0-4d7d-916e-4ac3eba13f91.png)
![image](https://user-images.githubusercontent.com/90667339/154377874-0b3f110c-64be-4b8f-8b38-8049c52bebf9.png)
![image](https://user-images.githubusercontent.com/90667339/154377983-74425cdc-60d3-46ac-a8ae-cba7879618d0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] run npm ci
- [x] cp .env.example .env
- [x] make sure "type": "module" is in package.json as it is required for node-fetch 
- [x] create a file called index.js under the server directory
- [x] create a package.json file
- [x] install node-fetch and express
- [x] import node-fetch and express to index.js
- [x] devised code with index.js so that when the client submit preferences, server does app.get '/yelp/:preference/:location'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] create a component for the navbar
- [x] create a component for the page-container
- [x] create a component for the home page
- [x] create a files for app.jsx and index.jsx under the pages directory
- [x] ensure that the client receive the correct data back from the server after they submit their preferences

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
