### ISSUE TITLE
Feature: User can have the app text the address of the location they are interested in to their phone

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to send a text message of the address of the location they are interested in to their phone.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user visits the result page, if the user would like to send the address to their phone so that they can navigate there using their default phone map app, they can click the "Send to your phone" button and input their phone number.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/155027417-0163bc79-90bd-445b-882b-a9c01cca5e78.png)
![image](https://user-images.githubusercontent.com/90667339/155026593-baeadd41-3f7f-4c2e-b0f1-b5acb12a06b1.png)
![image](https://user-images.githubusercontent.com/90667339/155026632-59ef27e2-c576-4188-8f27-352b3b14184c.png)
![image](https://user-images.githubusercontent.com/90667339/155026652-d1799cbc-7846-4770-9d9d-411849b557d6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Implement require twilio and assign it to the variable client
- [x] add code for an app.post for twilio to send a text message to the user when requested
- [x] ensure that the message of the text if the address of the result of the location on the client side

### ⚡ Client
- [x] create the button that the user will click to send a text message
- [x] create a modal that appears once the user clicks the button
- [x] ensure that the button and modal are designed to fit the theme of the page

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
