### ISSUE TITLE
Design Update: CSS and Design cleanup

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#13]
## ⚙️ Feature

> ##### Which feature is affected by this update?

The home and result page will be affected by this cleanup.  Font sizes and layouts may change to accommodate other screen sizes.  

## 📐 Plan

> ##### Summary of the technical approach to be taken.

To get started, I will be viewing this app on my mobile device to see what needs to be adjusted.  I will be starting on the home page and going through each component and feature to ensure that everything looks the way it should.  

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make the home page font mobile and desktop responsive
- [x] Adjust the layout of the result page so that it looks more organized
- [x] Ensure that the image of the result provided by yelp is contained and render as consistent as possible
- [x] Ensure that the modal properly contains all the elements and nothing is sticking out
