### ISSUE TITLE
Design Update: No result page 

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#15]
## ⚙️ Feature

> ##### Which feature is affected by this update?

If the user searches something but there are no results, a no result page will show.  A not-found page will also be added incase the user edits the url in an invalid way.  

## 📐 Plan

> ##### Summary of the technical approach to be taken.
Create a new component called no-result-found which will be rendered on the result page.  If the number of businesses from the results are 0, only this component will be rendered.  

Create a new page called page-not-found which will be rendered on app.jsx if the url is invalid

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![image](https://user-images.githubusercontent.com/90667339/155425545-d2756f04-48bf-4b3c-b1ab-f050dcd857e6.png)
![image](https://user-images.githubusercontent.com/90667339/155425593-dc541b09-de63-442a-acd5-f4a1e201632d.png)
![image](https://user-images.githubusercontent.com/90667339/155425626-741ac53b-6cb9-455d-b165-0db5def40786.png)
![image](https://user-images.githubusercontent.com/90667339/155425642-499539e1-b5b6-499e-91c2-6cb75121e595.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a no-result-found component
- [x] render the no-result-found element within the result page
- [x] Adjust handleSearch() within the result page so that if the result returns no businesses, show the no-result-found component only
- [x] Create a page-not-found page
- [x] render the page-not-found page within app.jsx if the url path is invalid
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
