### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up!

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will have the option of registering an account as a guest when first visiting the website.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.'
![image](https://user-images.githubusercontent.com/90667339/155461660-7e2faa9a-5845-48cd-8371-7c5378a47ca6.png)
![image](https://user-images.githubusercontent.com/90667339/155461724-a956f5f6-8ebf-43a3-b325-a12ce12244f4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a table for userId, username, hashedPassword, and createdAt
- [x] Update `data.sql` to  insert into "users"

### ☁️ Server

- [x] require argon2 and pg
- [x] add a app.post for when the user submits a sign up request
- [x] hash the password with argon2
- [x] ensure that the username and hashedPassword is successfully inserted into the database and if not, an error is caught

### ⚡ Client

- [x] Design the landing page for the user to sign-up for an account
- [x] Create a fetch method that is used when the user submits their new username and password
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
