### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in with an existing account.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user creates an account by signing up, they will be able to sign in and use the app.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/155639673-1a402a21-e67d-49d4-a7c7-9bd161acf95e.png)
![image](https://user-images.githubusercontent.com/90667339/155639704-502d6122-44fe-414c-b898-ea4a6a051a3c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update index.js so that it can handle a sign in request with app.post
- [x] include errors if the user does not have the correct credentials

### ⚡ Client

- [x] Update the auth-form to include text for sign in if the hash value reflects sign-in
- [x] Ensure that the guest sign in button logins the user in as a pre-determined guest credential
- [x] Check that the user can stay signed in after signing in

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
