### ISSUE TITLE
Feature: User can save locations into their bookmarks

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
The user will be able to bookmark locations they find interesting and want to view again later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Once the user finds a result, they will be able to hit the bookmark button to save a location they are interested in.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/155824253-25715d2f-cd36-441c-9d24-fe097f3d28a7.png)
![image](https://user-images.githubusercontent.com/90667339/155824273-fa491600-2873-437f-8934-cfea9594e133.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] update schema to create a new table for bookmarks
- [x] run npm run db:import when schema has been updated

### ☁️ Server

- [x] Update index.js to use app.post() to save the location information on the database should the client choose to
- [x] ensure that the data is being inserted corrected into the database with the correct userId

### ⚡ Client
- [x] Create a button that will give the ability for the user to bookmark locations
- [x] Create a function that will fetch to the server to save the location in the database
- [x] Ensure that the users unique userId is being sent to the server as well

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
