### ISSUE TITLE
Feature: User can try for another recommendation

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able try again for another search recommendation.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user has typed in their preference, location, and hits the submit button, they will be taken to a result page which will show the location name and address.  If the user is not satisfied with their result, they can have the app try again by hitting the try again button.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/154547973-0d2999f5-db26-4e39-81e8-4b2a80baffd1.png)
![image](https://user-images.githubusercontent.com/90667339/154548081-fbbdc0c7-31c1-4ca9-8140-5eb980c8d0e2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a ternary within the navbar component to have the "Try Again" anchor show only when the user is visiting the result page.  
- [x] The result should still be within the same parameters originally given by the user

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
