### ISSUE TITLE
Feature: User can view bookmarks

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of bookmarks and click each bookmark to view then for full details.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Once the user signs in and bookmarks a business, they can view a list of the bookmarks and click on each bookmark for full details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/157740119-4f0799c9-dac6-48b2-b2e1-76bd7bcec3a7.png)
![image](https://user-images.githubusercontent.com/90667339/157740215-4f59a888-c173-41f7-b9c0-a18ce6bc3182.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update index.js to handle a get request to db.query that checks whether the user has a specific business bookmarked already
- [x] Update index.js to handle a get request to db.query that provides the detail of the business to the client when the user clicks on a listed bookmark.

### ⚡ Client
- [x] Create a bookmark page that shows a list of bookmarks for the user
- [x] If there are no bookmarked businesses for that user, there should be a message saying no bookmarks
- [x] Ensure that the user can only see their own bookmarks and not any other user
- [x] Create a page that shows the business details if the user clicks on a listed bookmark.  It should be the same layout as the result page

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
