### ISSUE TITLE
Feature: User can delete bookmarks

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#34]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to delete bookmarks from their database if they are no longer interested in viewing this again.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As soon as the user bookmarks something, they can view the list of bookmarks and then hit the bookmark button again when viewing the page to remove it.  The user can also remove bookmarks when randomly searching locations from the home page if the location rendered by the app is something the user has already bookmarked.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/159373937-8bdf89c1-cb1c-4e09-9c0e-57c374817adc.png)
![image](https://user-images.githubusercontent.com/90667339/159373971-f17a10b6-be53-465f-a541-5cbe8f59f915.png)
![image](https://user-images.githubusercontent.com/90667339/159373997-78786333-36cd-4e6a-baf9-ed4833a3bd5e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Ensure the bookmark is removed from the database when the user removes the bookmark on the client side.  

### ☁️ Server

- [x] form a app.delete within index.s for the server to handle a delete request from the user to the database
- [x] the server should expect a token in order for this to work
- [x] ensure that it is deleting the correct business using the businessId **and** userId

### ⚡ Client

- [x] Add an event listener to the highlighted bookmark button which will initiate a delete request to the server when the user clicks on it
- [x] if the user is on the bookmark details page and hits the bookmark button, it should remove the business from the database but the page should not refresh and the user can still see the details on the page after clicking the button
- [x] After the user successfully deletes a bookmark, bring the user back to the bookmark list

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
