### ISSUE TITLE
Refactor:  Combine the fetch of the result location and reviews into 1 endpoint for the client instead of 2

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#44]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.
- [x] combine the search result endpoint and the reviews endpoint
- [x] return the client one object that contains all the necessary data
- [x] test and fix any bugs
- [x] remove console.logs
