### ISSUE TITLE
Refactor:  Add better error handling and messages on the FE so users know what went wron

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#46]
## ✅ Task List

- [x] Looking into using React Query
- [x] add next(err) on errors from the BE
- [ ] Add error messages for the user if there are no results found
- [ ] Add error messages for the user if they are unable to log in properly
- [ ] Test and fix for bugs
