### ISSUE TITLE
Feature: User can view the location on a map using google maps api

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view the location of their result on google maps

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user types in their preferences and location, they will taken to a result page to view the result along with the location being viewed on google maps.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90667339/154558262-67a36373-f7dd-4551-ba8a-2c826b9a4b49.png)
![image](https://user-images.githubusercontent.com/90667339/154558329-72e75c0b-1e66-4023-8a15-cae1198ed824.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client
- [x] Download react-google-maps "npm i -S @react-google-maps/api"
- [x] Create a google maps function component 
- [x] Render the google maps react element within the result page
- [x] Pass the latitude and longitude data received from the yelp api as a prop into the google maps component
- [x] Ensure that map is accurate by checking the address separately
- [x] Ensure that the map is positioned on the result page correctly

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
