### ISSUE TITLE
Design Update: The preference input element will become a select element

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#7]
## ⚙️ Feature

> ##### Which feature is affected by this update?
The home page of this app will have one select element with a list of preferences to optionally choose from, followed by an input element for location which is required.  

## 📐 Plan

> ##### Summary of the technical approach to be taken.
First I will replace the input element with a select element.  Then I will add the various option elements the user can choose from.  Lastly, I will adjust the styling of the element if necessary to keep the theme of the app consistent.  

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/90667339/154620587-aabdc83a-8b33-47e9-b9c1-661ad9e6a015.png)
![image](https://user-images.githubusercontent.com/90667339/154620625-83e2a786-09a1-449f-99a2-9c63ee4fb8d4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Replace input with select element
- [x] Add options for the user to select from
- [x] Revise CSS on select element to match the theme if necessary

- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
