### ISSUE TITLE
Feature: User can read the reviews and ratings of a location

### ISSUE THREAD

**Issue by edtan094** [edtan094/nomnom#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
The user will be able to view the ratings and read the reviews of the location

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user has inputted their preferences and location, they will be taken to a result page where they can see their result, along with the new feature of being able to see how many stars out of 5 the location is rated, and read 3 reviews in an accordion.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/90667339/154751727-cf86fbf2-981f-480d-a820-816d4c53515b.png)
![image](https://user-images.githubusercontent.com/90667339/154751765-e0b47db7-8a95-4e46-9333-4fbb4dd92c83.png)
![image](https://user-images.githubusercontent.com/90667339/154752899-ae440f4a-f2a9-4119-af71-a2ab0474e873.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Ensure that the code in server index.js already pulls the data for reviews and ratings from yelp.  If not, adjust code accordingly

### ⚡ Client

- [x] Add a state for reviews and ratings with the result page
- [x] Adjust the fetch request then methods so that it sets the review and ratings in the state 
- [x] Add star like elements to represent the ratings
- [x] Ensure the CSS and styling is aligned with the location information on the result page
- [x] Add the accordion element onto the bottom of the page where it will show the reviews from yelp
- [x] Ensure that the accordion works by only showing one review at a time
- [x] Style the accordion with CSS so that it matches the theme of the page

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
